### ISSUE TITLE
Traceback on git commit

### ISSUE THREAD

**Issue by mattrowe** [jzempel/continuity#45]
I just did a "sudo yum update" on an ec2 instance, and now continuity is throwing this error on a git commit:

```python
Traceback (most recent call last):
  File "/usr/bin/continuity", line 9, in <module>
    load_entry_point('continuity==0.9.8', 'console_scripts', 'continuity')()
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 521, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 2632, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 2312, in load
    return self.resolve()
  File "/usr/lib/python2.6/dist-packages/pkg_resources/__init__.py", line 2318, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.6/site-packages/continuity/cli/__init__.py", line 12, in <module>
    from .commons import get_commands
  File "/usr/lib/python2.6/site-packages/continuity/cli/commons.py", line 15, in <module>
    from continuity.services.commons import ServiceException
  File "/usr/lib/python2.6/site-packages/continuity/services/commons.py", line 14, in <module>
    from requests.packages.urllib3 import disable_warnings
ImportError: No module named packages.urllib3
```

**Comment by jzempel** [comment]
Hey @mattrowe, if I'm reading this right, you installed continuity on your ec2 system python (via `pip install continuity`?) and then subsequently updated your system via `sudo yum update`. It looks like that subsequent update screwed up the `requests` [version dependency](https://github.com/jzempel/continuity/blob/master/setup.py#L23).

You can re-run `pip install continuity` to restore its dependencies. But it's recommended that you keep continuity sandboxed so this doesn't happen. The homebrew install does this for OSX. But you can achieve the same affect on *nix by downloading continuity and running `make` (which builds and deposits a self-contained binary in /usr/local/bin).
